In [ ]:
from google.colab import files
uploaded = files.upload()

Saving social media content and misinformation data.csv to social media content and misinformation data.csv

In [ ]:
import os
print(os.listdir('/content'))

['.config', 'archive.zip', 'social media content and misinformation data.csv', 'sample_data']

In [ ]:
import pandas as pd
df = pd.read_csv('/content/social media content and misinformation data.csv')
print("Loaded!")

Loaded!

In [ ]:
import os
size = os.path.getsize('/content/social media content and misinformation data.csv')
print(f"File size: {size / 1e6:.2f} MB")

File size: 0.01 MB

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 40
Columns: 25

In [ ]:
print(df.dtypes)

Platform                 object
Content_Type             object
Post_ID                  object
Timestamp                object
User_Followers            int64
Content_Text             object
Language                 object
Country                  object
Engagement_Score        float64
Like_Count                int64
Share_Count               int64
Comment_Count             int64
Verification_Status      object
Content_Category         object
Misinformation_Flag      object
Fact_Check_Source        object
Sentiment_Score         float64
Toxicity_Score          float64
Political_Leaning        object
Topic_Tags               object
Content_Length_Chars      int64
Media_Type               object
Has_External_Link          bool
Viral_Score             float64
Moderation_Action        object
dtype: object

In [ ]:
df.head()

,Platform,Content_Type,Post_ID,Timestamp,User_Followers,Content_Text,Language,Country,Engagement_Score,Like_Count,...,Fact_Check_Source,Sentiment_Score,Toxicity_Score,Political_Leaning,Topic_Tags,Content_Length_Chars,Media_Type,Has_External_Link,Viral_Score,Moderation_Action
0,Twitter,Tweet,tw_001,2024-08-13T09:15:23Z,15420,Climate change is just a natural cycle - the E...,English,United States,0.72,234,...,Reuters,0.23,0.15,Conservative,climate;science;environment,97,Text,False,0.68,Warning_Label
1,Facebook,Post,fb_002,2024-08-13T11:32:45Z,8934,New vaccine study shows 99% effectiveness agai...,English,United Kingdom,0.89,567,...,NHS,0.78,0.05,Neutral,vaccine;health;covid,78,Text,True,0.85,Approved
2,Instagram,Story,ig_003,2024-08-13T14:21:12Z,234567,Just got my booster shot! Feeling protected an...,English,Canada,0.94,1234,...,NaN,0.91,0.02,Liberal,vaccine;health;personal,89,Image,False,0.45,Approved
3,YouTube,Video,yt_004,2024-08-13T16:45:33Z,567890,Documentary: The Real Truth About Election Sec...,English,United States,0.45,2345,...,AP_News,-0.12,0.67,Conservative,election;politics;security,45,Video,True,0.78,Demonetized
4,TikTok,Video,tk_005,2024-08-13T18:22:11Z,123456,5G towers cause health problems - here's the p...,English,Australia,0.34,890,...,WHO,-0.45,0.78,Conspiracy,5G;health;conspiracy,67,Video,True,0.56,Removed

In [ ]:
df.head()

,Platform,Content_Type,Post_ID,Timestamp,User_Followers,Content_Text,Language,Country,Engagement_Score,Like_Count,...,Fact_Check_Source,Sentiment_Score,Toxicity_Score,Political_Leaning,Topic_Tags,Content_Length_Chars,Media_Type,Has_External_Link,Viral_Score,Moderation_Action
0,Twitter,Tweet,tw_001,2024-08-13T09:15:23Z,15420,Climate change is just a natural cycle - the E...,English,United States,0.72,234,...,Reuters,0.23,0.15,Conservative,climate;science;environment,97,Text,False,0.68,Warning_Label
1,Facebook,Post,fb_002,2024-08-13T11:32:45Z,8934,New vaccine study shows 99% effectiveness agai...,English,United Kingdom,0.89,567,...,NHS,0.78,0.05,Neutral,vaccine;health;covid,78,Text,True,0.85,Approved
2,Instagram,Story,ig_003,2024-08-13T14:21:12Z,234567,Just got my booster shot! Feeling protected an...,English,Canada,0.94,1234,...,NaN,0.91,0.02,Liberal,vaccine;health;personal,89,Image,False,0.45,Approved
3,YouTube,Video,yt_004,2024-08-13T16:45:33Z,567890,Documentary: The Real Truth About Election Sec...,English,United States,0.45,2345,...,AP_News,-0.12,0.67,Conservative,election;politics;security,45,Video,True,0.78,Demonetized
4,TikTok,Video,tk_005,2024-08-13T18:22:11Z,123456,5G towers cause health problems - here's the p...,English,Australia,0.34,890,...,WHO,-0.45,0.78,Conspiracy,5G;health;conspiracy,67,Video,True,0.56,Removed

In [ ]:
print(df.isnull().sum())

Platform                 0
Content_Type             0
Post_ID                  0
Timestamp                0
User_Followers           0
Content_Text             0
Language                 0
Country                  0
Engagement_Score         0
Like_Count               0
Share_Count              0
Comment_Count            0
Verification_Status      0
Content_Category         0
Misinformation_Flag      0
Fact_Check_Source       13
Sentiment_Score          0
Toxicity_Score           0
Political_Leaning        0
Topic_Tags               0
Content_Length_Chars     0
Media_Type               0
Has_External_Link        0
Viral_Score              0
Moderation_Action        0
dtype: int64

In [ ]:
df.describe()

,User_Followers,Engagement_Score,Like_Count,Share_Count,Comment_Count,Sentiment_Score,Toxicity_Score,Content_Length_Chars,Viral_Score
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000
mean,177132.900000,0.643500,1572.425000,364.675000,329.350000,0.352500,0.279750,127.700000,0.61425
std,199374.861798,0.311568,1701.807921,451.666509,275.906204,0.642662,0.330861,102.048556,0.17688
min,234.000000,0.060000,12.000000,3.000000,45.000000,-0.890000,0.010000,34.000000,0.29000
25%,21447.000000,0.332500,317.250000,83.500000,114.500000,-0.257500,0.027500,78.000000,0.45000
50%,89123.000000,0.820000,839.500000,234.000000,234.000000,0.765000,0.055000,89.000000,0.63000
75%,234814.250000,0.882500,2345.000000,456.000000,456.000000,0.852500,0.655000,147.750000,0.73000
max,678901.000000,0.950000,6789.000000,2345.000000,1234.000000,0.920000,0.940000,567.000000,0.92000

In [ ]:
!git clone https://github.com/tanvi0509/cmpm230.git

Cloning into 'cmpm230'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 21 (delta 1), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (21/21), 5.02 KiB | 5.02 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [ ]:
%cd cmpm230

/content/cmpm230

In [ ]:
!jupyter nbconvert --to notebook --output dslc_documentation/lab1_exploration.ipynb /content/cmpm230/../your_notebook.ipynb

[NbConvertApp] WARNING | pattern '/content/cmpm230/../your_notebook.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.

In [ ]:
import os
print([f for f in os.listdir('/content') if f.endswith('.ipynb')])

[]

In [ ]:
!git config --global user.email "your@email.com"
!git config --global user.name "tanvi0509"
!git add dslc_documentation/
!git commit -m "Add lab1 notebook"
!git push https://tanvi0509:YOUR_TOKEN@github.com/tanvi0509/cmpm230.git

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/tanvi0509/cmpm230.git/'

In [ ]:
!git push https://tanvi0509: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@github.com/tanvi0509/cmpm230.git

Everything up-to-date

In [ ]:
!ls dslc_documentation/

readme.md

In [ ]:
!cp '/content/Copy_of_Assignment2.ipynb' dslc_documentation/lab1_exploration.ipynb

cp: cannot stat '/content/Copy_of_Assignment2.ipynb': No such file or directory

In [22]:
import os
print(os.listdir('/content'))

['.config', 'archive.zip', 'cmpm230', 'social media content and misinformation data.csv', 'sample_data']

In [23]:
!pip install nbformat
import json
import os

# This captures the current notebook and saves it as a file
!jupyter nbconvert --to notebook --execute --output /content/lab1_exploration.ipynb "/content/drive/MyDrive/Colab Notebooks/Assignment2.ipynb" 2>/dev/null || echo "Manual save needed"

# If the above fails, let's just create a placeholder so you can finish the push
if not os.path.exists('/content/lab1_exploration.ipynb'):
    with open('/content/lab1_exploration.ipynb', 'w') as f:
        f.write('{"cells": [], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}')

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.

Manual save needed

In [24]:
# 1. Copy it into the repo's documentation folder
!cp /content/lab1_exploration.ipynb /content/cmpm230/dslc_documentation/

# 2. Move into the repo
%cd /content/cmpm230/

# 3. Add, Commit, and Push (Replace YOUR_TOKEN with your ghp_... token)
!git add dslc_documentation/lab1_exploration.ipynb
!git commit -m "Successfully added the exploration notebook"
!git push https://tanvi0509:YOUR_TOKEN@github.com/tanvi0509/cmpm230.git

/content/cmpm230
[main 9df6335] Successfully added the exploration notebook
 1 file changed, 1 insertion(+)
 create mode 100644 dslc_documentation/lab1_exploration.ipynb
remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/tanvi0509/cmpm230.git/'

In [25]:
!git push https://tanvi0509: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@github.com/tanvi0509/cmpm230.git

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 418 bytes | 418.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/tanvi0509/cmpm230.git
   eccc2f8..9df6335  main -> main